[package]
name = "rust-thumbnail"
version = "0.1.0"
edition = "2021"
author="SegFault"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify= "6.0.1"